[package]
name = "rivet-process-supervisor-embed"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.87"

[dev-dependencies]
tempfile = "3.12.0"

[build-dependencies]
sha2 = "0.10.8"
