[package]
name = "rivet-toolchain"
version = "0.1.0"
edition = "2021"
build = "build.rs"
license = "MIT"
rust-version = "1.75"
description = "Managed game servers, matchmaking, and DDoS mitigation that lets you focus on building your game."
homepage = "https://rivet.gg"
repository = "https://github.com/rivet-gg/cli"

[dependencies]
# Disable less common file formats. Preserve TOML for backwards compatibility.
# This is pointing to a fork that contains a fix for Byte-order marks on Windows.
async-posthog = { git = "https://github.com/rivet-gg/posthog-rs.git", rev = "ef4e80e" }
async-stream = "0.3.3"
config = { git = "https://github.com/rivet-gg/config-rs", rev = "0f3c89b4770276e8db72ce962974a9a72c59c97a", default-features = false, features = ["json", "async"] }
console = "0.15"
ctrlc = { version = "3.2", features = ["termination"] }
dirs = "5.0"
fs_extra = "1.2.0"
futures-util = "0.3"
global-error = {  git = "https://github.com/rivet-gg/rivet.git", rev = "22baf31efa3ffcdad65ecc72ce25425ab61b9c6f" }
home = "0.5.3"
humansize = "1.1"
ignore = "0.4"
indicatif = "0.17"
lz4 = "1.24"
mime_guess = "2.0"
open = "5.3.0"
rand = "0.8"
regex = "1.10"
reqwest = { version = "0.11", default-features = false, features = ["stream", "blocking", "rustls-tls"] }
rivet-api = { package = "rivet-api-ee", path = "../../sdks/rust" }
sentry = { version = "0.32", default-features = false, feature = ["rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
strum = { version = "0.24", features = ["derive"] }
sysinfo = "0.30.0"
portpicker = "0.1"
tabled = "0.8.0"
tar = "0.4.40"
tempfile = "3.2"
term_size = "0.3.2"
thiserror = "1.0"
tokio = { version = "1.27", default-features = false, features = ["fs", "macros", "process", "rt"] }
tokio-util = { version = "0.7", default-features = false, features = ["io-util"] }
tower = "0.4.12"
typed-path = "0.7.0"
url = "2.5.0"
uuid = { version = "1.3", features = ["v4"] }
webbrowser = "0.8.7"
which = "5.0.0"
zip = "0.5"
const_format = "0.2.32"
pkg-version = "1.0.0"
fd-lock = "4.0.2"
include_dir = "0.7.4"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", default-features = false, features = ["user", "signal"] }

[dev-dependencies]
assert_cmd = "2.0"

[build-dependencies]
anyhow = "1.0"
vergen-git2 = "1.0.0"

