[package]
name = "rivet-deno-embed"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
fd-lock = "4.0.2"
reqwest = { version = "0.11", default-features = false, features = ["stream", "blocking", "rustls-tls"] }
tempfile = "3.2"
tokio = { version = "1.38.1", features = ["full"] }
zip = "0.5"

