[package]
name = "rivet-deno-embed"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.40.0", features = ["full"] }

[features]
# Enable if using from a build script, since this'll cause problems if cross
# compiling.
ignore-override-target = []

[build-dependencies]
dirs = "5.0.1"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0.128"
zip = "0.5"

[dev-dependencies]
tempfile = "3.12.0"

