[package]
name = "rivet-deno-embed"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.38.1", features = ["full"] }

[build-dependencies]
dirs = "5.0.1"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0.128"
zip = "0.5"

[dev-dependencies]
tempfile = "3.12.0"

