[package]
name = "rivet-toolchain-ffi"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.75"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.5.0"
serde_json = "1.0"
tokio = { version = "1.40.0", default-features = false, features = ["rt"] }
toolchain = { path = "../toolchain/", package = "rivet-toolchain" }

