[package]
name = "rivet-process-runner"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rivet-process-runner"

[dependencies]
ctrlc = { version = "3.4.5", features = ["termination"] }
lazy_static = "1.5.0"
rivet-process-runner-shared = { path = "../process-runner-shared" }
signal-hook = { version = "0.3.17", features = ["iterator"], default-features = false }
thiserror = "1.0.63"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29.0", features = ["process", "signal"], default-features = false }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.48", features = ["Win32_Foundation", "Win32_System_Console", "Win32_System_Threading"] }
