/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeCloudOpengbProjectsEnvsListResponse {
    #[serde(rename = "environments")]
    pub environments: Vec<crate::models::EeOpengbEnvironment>,
}

impl EeCloudOpengbProjectsEnvsListResponse {
    pub fn new(environments: Vec<crate::models::EeOpengbEnvironment>) -> EeCloudOpengbProjectsEnvsListResponse {
        EeCloudOpengbProjectsEnvsListResponse {
            environments,
        }
    }
}


