[package]
name = "rivet-cli"
version = "2.0.0-rc.4"
edition = "2021"
rust-version = "1.75"
repository = "https://github.com/rivet-gg/cli"

[[bin]]
name = "rivet"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
toolchain = { version = "0.1.0", path = "../toolchain", package = "rivet-toolchain" }
tokio = { version = "1.38.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.120"
open = "5.3.0"
anyhow = "1.0"

[build-dependencies]
anyhow = "1.0"

[build-dependencies.vergen-git2]
version = "1.0.0"
features = [
  "build",
  "cargo",
  "rustc"
]

