[package]
name = "rivet-backend-embed"
version = "0.1.0"
build = "build.rs"
license = "Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
include_dir = "0.7.4"
tokio = "1.27"

[build-dependencies]
anyhow = "1.0"
rivet-deno-embed = { path = "../deno-embed" }
tempfile = "3.2"
tokio = "1.27"

