name: Test

on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # TODO: https://github.com/rivet-gg/cli/issues/211
        # os: [ubuntu-22.04, macos-12]
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05

      - name: Install Docker
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install docker
          colima start
          
      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        timeout-minutes: 10
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run cargo fmt
        run: |
          nix-shell --run "
            cargo fmt --check --manifest-path rivet-toolchain-ffi/Cargo.toml && 
            cargo fmt --check --manifest-path rivet-cli/Cargo.toml
          "

      - name: Run cargo test
        env:
          RIVET_API_ENDPOINT: ${{ secrets.RIVET_API_ENDPOINT }}
          RIVET_TOKEN: ${{ secrets.RIVET_TOKEN }}
          RUST_BACKTRACE: 1
          CARGO_PROFILE_TEST_BUILD_OVERRIDE_DEBUG: true
        run: |
          nix-shell --run "cargo test"

